import {
  Gamepad2,
  Smartphone,
  Laptop,
  Code,
  Globe,
  Brain,
  Building2,
  Calendar,
  Rocket,
  Wrench,
  Bot,
  Briefcase,
  GraduationCap,
  Building,
  Award,
  Scroll,
  Twitter,
  Instagram,
  Linkedin,
  Github,
  Download,
} from "lucide-react";

export const icons = {
  faGamepad: Gamepad2,
  faMobileAlt: Smartphone,
  faLaptopCode: Laptop,
  faCode: Code,
  faGlobe: Globe,
  faBrain: Brain,
  faBuilding: Building2,
  faCalendar: Calendar,
  faRocket: Rocket,
  faWrench: Wrench,
  faRobot: Bot,
  faBriefcase: Briefcase,
  faGraduationCap: GraduationCap,
  faUniversity: Building,
  faAward: Award,
  faScroll: Scroll,
  faXTwitter: Twitter,
  faInstagram: Instagram,
  faLinkedinIn: Linkedin,
  faGithub: Github,
  faDownload: Download,
} as const;

export type IconName = keyof typeof icons;
